# Generated by Django 3.1.1 on 2020-09-30 08:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('from_email', models.CharField(max_length=1000)),
                ('redirect_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('body', ckeditor.fields.RichTextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='PhishingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url_to_clone', models.CharField(max_length=1000)),
                ('template_dir', models.CharField(max_length=1000)),
                ('server_status', models.BooleanField(null=True)),
                ('port_number', models.IntegerField(blank=True, null=True)),
                ('site_url', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=1000)),
                ('smtp_server', models.CharField(max_length=1000)),
                ('smtp_port', models.IntegerField()),
                ('use_tls', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=1000)),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.targetgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent_status', models.BooleanField(null=True)),
                ('email_open_status', models.BooleanField(null=True)),
                ('link_clicked_status', models.BooleanField(null=True)),
                ('data_submitted_status', models.BooleanField(null=True)),
                ('data_submitted', models.TextField(null=True)),
                ('reported', models.BooleanField(null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campaign')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.target')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='phishing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.phishingpage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sending_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sendingprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.targetgroup'),
        ),
    ]
